# Generated by Django 4.0.2 on 2022-05-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Busroutes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', related_query_name='my_bus', to='Ticketapp.busroutes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Ticket_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Ticketapp.ticket_details'),
        ),
        migrations.AlterField(
            model_name='ticket_details',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='my_ticket', to='Ticketapp.bus'),
        ),
    ]
