# Generated by Django 4.0.2 on 2022-05-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0002_remove_bus_booking_date_busroutes_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bookingdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_details',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='my_ticket', to='Ticketapp.bus'),
        ),
    ]
