# Generated by Django 4.0.2 on 2022-05-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0003_bus_bookingdate_alter_ticket_details_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bookingdate',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='busroutes',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='busroutes',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_date',
        ),
    ]
