# Generated by Django 4.0.2 on 2022-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0004_rename_bookingdate_bus_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroutes',
            name='pricelist',
            field=models.CharField(max_length=70),
        ),
    ]
